name: Test and Deploy
on: [push, workflow_dispatch]
env:
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: random-address
      MONGODB_USERNAME: random-username
      MONGODB_PASSWORD: random password
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v3
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install NodeJs
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependency
      run: npm ci
    - name: Run Code
      run: node test.js
    - name: ouput variable
      run: |
        echo "MONGO_USERNAME": ${{ env.MONGODB_USERNAME }}
  deploy:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
    - name: Get Code
      uses: actions/checkout@v3
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install NodeJs
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependency
      run: npm ci
    - name: Build
      run: npm run build
    - name: Publish JS filename
      id: publish
      run: find build/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-folder
        path: build
    - name: deploy
      run: echo "Deploying...."
  output:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Access Artifact
      uses: actions/download-artifact@v3
      with:
        name: build-folder
    - name: Output Contents
      run: echo "${{ needs.deploy.outputs.script-file }}"
    - name: log artifacts
      run: ls




